

variables:
  S3_BUCKET_NAME: "testapp-tagger"



cache:
  paths:
    - node_modules/
pages:
before_script:
  - npm install
  image: node
  script:
    - npm run build
    - mkdir -p ./public
    - cp ./** ./public/
  artifacts:
    paths:
      - dist
  only:
    - master

deploy:
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp ./ s3://$S3_BUCKET_NAME/ --recursive
