

variables:
  S3_BUCKET_NAME: "testapp-tagger"


cache:
  paths:
    - node_modules/


stage:
  before_script:
    - npm install
  image: node
  script:
    - npm run build
    - mkdir -p ./public
    - cp ./dist/** ./public/
  artifacts:
    paths:
      - dist
  only:
    - master

deploy_production:
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp ./dist s3://$S3_BUCKET_NAME/ --recursive
