

variables:
  S3_BUCKET_NAME: "testapp-tagger"


cache:
  paths:
    - node_modules/


build:
  stage: build
  before_script:
    - npm install
  image: node
  script:
    - npm run build
    - mkdir -p ./public
    - ls
    - cp ./dist/** ./public/
  artifacts:
    paths:
      - dist/
    when: always

  only:
    - master

deploy_production:
  stage: deploy
  image: python:latest
  script:
  - pip install awscli
  - ls
  - aws s3 cp ./dist s3://$S3_BUCKET_NAME/ --recursive
