image: node

variables:
  S3_BUCKET_NAME: "testapp-tagger"

before_script:
  - npm install

cache:
  paths:
    - node_modules/
pages:
  script:
    - npm run build
  artifacts:
    paths:
      - dist
  only:
    - master

deploy:
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp ./ s3://$S3_BUCKET_NAME/ --recursive
